/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.photostorage;

import com.mycompany.photostorage.model.NewPhoto;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.activation.MimetypesFileTypeMap;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author m_ligus
 */
public class AddPhotoPanel extends javax.swing.JPanel {

    private File[] photos;
    /**
     * Creates new form AddPhotoPanel
     */
    public AddPhotoPanel() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectPhotoButton = new javax.swing.JButton();

        selectPhotoButton.setText("Select Photos");
        selectPhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPhotoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(selectPhotoButton)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(selectPhotoButton)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void selectPhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPhotoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            photos = fileChooser.getSelectedFiles();
        }
        List<File> imageFile = new ArrayList<>();
        for (int i = photos.length-1;i>=0;i--) {
            String mimeType;
            mimeType = new MimetypesFileTypeMap().getContentType( photos[i] );
            String fileType = mimeType.split("/")[0];
            if (fileType.equalsIgnoreCase("image")) {
                imageFile.add(photos[i]);
            }
        }
        
        List<NewPhoto> newPhotos = new ArrayList<>(); //placeholder - i just need to remember what to do ^.^
        for (File file : imageFile) {
            newPhotos.add(new NewPhoto());
        }
    }//GEN-LAST:event_selectPhotoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton selectPhotoButton;
    // End of variables declaration//GEN-END:variables
}
