package com.mycompany.photostorage.entity;
// Generated 2017-04-25 22:04:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="photokeeper"
)
public class Category  implements java.io.Serializable {


     private Integer idc;
     private Category category;
     private User user;
     private String name;
     private Set<Photo> photos = new HashSet<Photo>(0);
     private Set<Category> categories = new HashSet<Category>(0);

    public Category() {
    }

	
    public Category(User user, String name) {
        this.user = user;
        this.name = name;
    }
    public Category(Category category, User user, String name, Set<Photo> photos, Set<Category> categories) {
       this.category = category;
       this.user = user;
       this.name = name;
       this.photos = photos;
       this.categories = categories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idc", unique=true, nullable=false)
    public Integer getIdc() {
        return this.idc;
    }
    
    public void setIdc(Integer idc) {
        this.idc = idc;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Category_idc")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="User_idu", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Photo> getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set<Photo> photos) {
        this.photos = photos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Category> getCategories() {
        return this.categories;
    }
    
    public void setCategories(Set<Category> categories) {
        this.categories = categories;
    }




}


