package com.mycompany.photostorage.entity;
// Generated 2017-04-25 22:04:09 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DeviceId generated by hbm2java
 */
@Embeddable
public class DeviceId  implements java.io.Serializable {


     private int idd;
     private int typeOfDeviceIdtod;

    public DeviceId() {
    }

    public DeviceId(int idd, int typeOfDeviceIdtod) {
       this.idd = idd;
       this.typeOfDeviceIdtod = typeOfDeviceIdtod;
    }
   


    @Column(name="idd", unique=true, nullable=false)
    public int getIdd() {
        return this.idd;
    }
    
    public void setIdd(int idd) {
        this.idd = idd;
    }


    @Column(name="TypeOfDevice_idtod", nullable=false)
    public int getTypeOfDeviceIdtod() {
        return this.typeOfDeviceIdtod;
    }
    
    public void setTypeOfDeviceIdtod(int typeOfDeviceIdtod) {
        this.typeOfDeviceIdtod = typeOfDeviceIdtod;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DeviceId) ) return false;
		 DeviceId castOther = ( DeviceId ) other; 
         
		 return (this.getIdd()==castOther.getIdd())
 && (this.getTypeOfDeviceIdtod()==castOther.getTypeOfDeviceIdtod());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdd();
         result = 37 * result + this.getTypeOfDeviceIdtod();
         return result;
   }   


}


