package com.mycompany.photostorage.entity;
// Generated 2017-04-27 12:42:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Device generated by hbm2java
 */
@Entity
@Table(name="device"
    ,catalog="photokeeper"
    , uniqueConstraints = {@UniqueConstraint(columnNames="idd"), @UniqueConstraint(columnNames="name")} 
)
/**
 * Class representing storing device
 */
public class Device  implements java.io.Serializable {


     private int idd;
     private Typeofdevice typeofdevice;
     private String name;
     private String capacity;
     private String freeSpace;
     private byte isClosed;
     private Set<Photo> photos = new HashSet<Photo>(0);

    /**
     * Basic constructor
     */
    public Device() {
    }

    /**
     * Constructor for empty device
     * @param typeofdevice type of the device
     * @param name name of the device
     * @param capacity capacity of the device
     * @param freeSpace free space left on the device
     * @param isClosed information if device is closed and cant storage photos anymore
     */
    public Device(Typeofdevice typeofdevice, String name, String capacity, String freeSpace, byte isClosed) {
       
        this.typeofdevice = typeofdevice;
        this.name = name;
        this.capacity = capacity;
        this.freeSpace = freeSpace;
        this.isClosed = isClosed;
    }
    
    /**
     * Constructor for device having photos
     * @param typeofdevice type of the device
     * @param name name of the device
     * @param capacity capacity of the device
     * @param freeSpace free space left on the device
     * @param isClosed information if device is closed and cant storage photos anymore
     * @param photos stored photos
     */
    public Device(Typeofdevice typeofdevice, String name, String capacity, String freeSpace, byte isClosed, Set<Photo> photos) {
       this.typeofdevice = typeofdevice;
       this.name = name;
       this.capacity = capacity;
       this.freeSpace = freeSpace;
       this.isClosed = isClosed;
       this.photos = photos;
    }
   
    @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idd", unique=true, nullable=false)
    public int getIdd() {
        return this.idd;
    }
    
    public void setIdd(int id) {
        this.idd = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="TypeOfDevice_idtod", nullable=false, insertable=true, updatable=true)
    public Typeofdevice getTypeofdevice() {
        return this.typeofdevice;
    }
    
    public void setTypeofdevice(Typeofdevice typeofdevice) {
        this.typeofdevice = typeofdevice;
    }

    
    @Column(name="name", unique=true, nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="capacity", nullable=false, length=50)
    public String getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(String capacity) {
        this.capacity = capacity;
    }

    
    @Column(name="freeSpace", nullable=false, length=50)
    public String getFreeSpace() {
        return this.freeSpace;
    }
    
    public void setFreeSpace(String freeSpace) {
        this.freeSpace = freeSpace;
    }

    
    @Column(name="isClosed", nullable=false)
    public byte getIsClosed() {
        return this.isClosed;
    }
    
    public void setIsClosed(byte isClosed) {
        this.isClosed = isClosed;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="device_has_photo", catalog="photokeeper", joinColumns = { 
        @JoinColumn(name="Device_idd", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Photo_idp", nullable=false, updatable=false) })
    public Set<Photo> getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set<Photo> photos) {
        this.photos = photos;
    }




}


