package com.mycompany.photostorage.entity;
// Generated 2017-04-25 22:04:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Typeofdevice generated by hbm2java
 */
@Entity
@Table(name="typeofdevice"
    ,catalog="photokeeper"
)
public class Typeofdevice  implements java.io.Serializable {


     private Integer idtod;
     private String description;
     private String singleSave;
     private Set<Device> devices = new HashSet<Device>(0);

    public Typeofdevice() {
    }

	
    public Typeofdevice(String description) {
        this.description = description;
    }
    public Typeofdevice(String description, String singleSave, Set<Device> devices) {
       this.description = description;
       this.singleSave = singleSave;
       this.devices = devices;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtod", unique=true, nullable=false)
    public Integer getIdtod() {
        return this.idtod;
    }
    
    public void setIdtod(Integer idtod) {
        this.idtod = idtod;
    }

    
    @Column(name="description", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="singleSave", length=45)
    public String getSingleSave() {
        return this.singleSave;
    }
    
    public void setSingleSave(String singleSave) {
        this.singleSave = singleSave;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="typeofdevice")
    public Set<Device> getDevices() {
        return this.devices;
    }
    
    public void setDevices(Set<Device> devices) {
        this.devices = devices;
    }




}


